### ISSUE TITLE
Relationship Extraction Containers

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/RelationshipsG3#18]
- [x] set up containers
- [ ] add common API to containers (#15)

we currently use two algorithms: Ollie & OpenIE

**Comment by pfent** [comment]
Just keep the algorithm [exchangeable](https://en.wikipedia.org/wiki/Strategy_pattern) :+1:

**Comment by Henni** [comment]
This is done, right @ansjin ?

**Comment by ansjin** [comment]
Yeah this is done!! All our algorithms can run in different containers with a main app as the common API point!

We can close this!
