### ISSUE TITLE
Implement data retrieval / preprocessing

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/RelationshipsG3#19]
- [ ] retrieve data from database
- [ ] preprocess data to fit the relationship extraction API

**Comment by ansjin** [comment]
- we need to have an API for the first task to access the cloud and DB(https://github.com/MusicConnectionMachine/api/issues/17)
- For second we can start the pre-processing from the sample data provided by team 2 here (https://github.com/MusicConnectionMachine/UnstructuredData/issues/58)

**Comment by nbasargin** [comment]
Please discuss cloud data data format here: https://github.com/MusicConnectionMachine/UnstructuredData/issues/68

**Comment by Sandr0x00** [comment]
Retrieve Data from DB is continued here: https://github.com/MusicConnectionMachine/Relationships/issues/6
Reading of the WET-Files is continued here: https://github.com/MusicConnectionMachine/Relationships/issues/8
I think @ansjin did the preprocessing already in the algorithm containers.

**Comment by ansjin** [comment]
completed here https://github.com/MusicConnectionMachine/Relationships/issues/6
