### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/RelationshipsG3#2]
Hey @Henni @ansjin @krishenk @RBirkeland 

do you guys need help getting started? We are three days in and would love to see some progress to happen here on Github! 
Anything that is unclear? Already encountered blockers?

Lets us know, we are here to help!

Tasks:
- [x] Create starter issues
- [ ] Map out required technologies
- [ ] Research your topic
- [ ] Fork the repository
- [ ] Create some PRs
- [ ] Review, Merge and Repeat
- [ ] Keep :dancer: towards the goal

**Comment by ansjin** [comment]
Hey @kordianbruck and @Henni @krishenk @RBirkeland  guys, I have prepared a diagram of my understanding of the project can you check whether its correct or I have missed something ?

![relationship](https://cloud.githubusercontent.com/assets/10348337/23486885/eee78f70-fee2-11e6-9ab1-f93d5bd0ea8f.jpg)

**Comment by Henni** [comment]
@ansjin Great diagram!
A few notes / questions from my side:
* do we really only get the source links from the database? I would believe (read: "hope") that we also receive some information about the entities contained in this source and maybe also the position of the occurences.
* is it our job to create any of the components on the right of your graphic (i.e. the REST API)?

**Comment by kordianbruck** [comment]
I do agree @Henni: you need more information than just the URLs. Teams 1 & 2 will be in charge of supplying any data you require. Make sure you open issues in their repositories to let them know what it is exactly that you guys require.

On the second point: its up to you to check with teams 5 & 6 as well. If you coordinate correctly you can minimize duplicate work. Also create issues there to let them know you are thinking about these things. 

**Your team is the glue between the other teams!**

**Comment by ansjin** [comment]
@Henni 
First point: Yeah true, Lets discuss it further when we meet tomorrow.

Second Point: I am not sure how much we have to do,  I made that up because it was mentioned as part of the project B. We can check with team 5 and 6 about that  and avoid duplicate work as mentioned by @kordianbruck .

**Comment by Henni** [comment]
@RBirkeland hi, it would be great if you could sign up for gitter so that we can communicate in the future. We are also meeting today at 10:00 in the room 1.10.022B. So if you are on the campus maybe you can drop by.

**Comment by sacdallago** [comment]
@Henni we have pinged @RBirkeland . Please let us know if he made it to the meeting or has contacted you, otherwise we will try to find another student to join your team ASAP

**Comment by sacdallago** [comment]
A note on the issue at hand:

1. You will need _Entities_ from the first teams (composers, music pieces, historical period, current (romanticism, ...) ...). From these you can mine relationships. The relationships you can view in the most simple from as `{source: E1, target: E2, relationship: RelationshipN}`, you can encode the relationship to be directed (eg.:`E1-->E2`) by encoding this information in the relationship definition (eg.: `{relationship: RelationshipN, directed: true}`). The final data structure for relationships will obviously be bigger! For example: I can imagine storing in the relationship a `mined_from` attribute with where you got the relationship from and ad `score` given the attendance of that website or the score that the NLP device gives to it having picked up the right signal.

2. Where the API lies is still an open question. Historically, this should be @MusicConnectionMachine/group-1 and @MusicConnectionMachine/group-2 , I'm fairly sure that in these days we will see which direction this will go. You don't have to worry about that :)

**Comment by RBirkeland** [comment]
Hey guys, sorry, I joined this seminar late so haven't gotten all the info in the beginning, I just finished my last exam so from now on this is my sole focus. Sorry I couldn't come to the meeting today, I would highly appropriate a short summary :)

**Comment by RBirkeland** [comment]
If you guys are still at uni, I'm available now

**Comment by Henni** [comment]
I think we can close this. Further development will happen in more granular issues.
