### ISSUE TITLE
Subtract relations from Wikipedia

### ISSUE THREAD

**Issue by martomi** [MusicConnectionMachine/RelationshipsG3#22]
We had a discussion with @vviro and @gyachdav that the most interesting relations to discover with our tool would be the ones that are not already well-known and easily available on Wikipedia.

For this, it would be nice if you could extract the relationships from Wikipedia and offer an API which only provides us ( @MusicConnectionMachine/group-5 @MusicConnectionMachine/group-6 ) with the relationships that **don't** contain those relationships.

Before that, you might need to have the Wikipedia URLs for every entity extracted by @MusicConnectionMachine/group-1 or @MusicConnectionMachine/group-2 .

Also I'm posting this issue here, but I think it's also relevant for @MusicConnectionMachine/group-4 . Maybe decide which group can do it.

**Comment by kordianbruck** [comment]
@RBirkeland can you please comment on this?

**Comment by Sandr0x00** [comment]
We can't decide which group can do it is, since we all do the same. **Exactly** the same. It's not like we do one big whole like you guys, or G1/2.
So I will open an Issue in G4 for this too.
But to clarify things first:
- We don't work with Wikipedia-URLs, we work on text, given by G1/2.
- What do you mean with: "extract [...] relationships from Wikipedia and offer an API which only provides [...] relationships that don't contain those relationships."?

**Comment by martomi** [comment]
@Sandr00 Here's what I mean:

Let's say we have two relationships for `entity1` extracted from anywhere.

`entity1` - `relationA` - `entitiyX`
`entity1` - `relationB` - `entitiyY`

And let's say you extract only the following relationship from wikipedia:

`entity1` - `relationA` - `entitiyX`

Naturally, wikipedia doesn't provide all the relationships that you can gather from the aggregated data from all the sources. The suggestion is now that the most interesting relationships to observe would be the ones which are not easily available on wikipedia. To get those relationships you subtract the second set of relationships (wikipedia) from all mined relationships and get:

`entity1` - `relationB` - `entitiyY`

That was an idea that @vviro suggested. Does it make sense to you now?

**Comment by Henni** [comment]
@Sandr00 I believe we should be able to work together on this.
In my opinion this should be solved near the API, so after all the relationship extraction itself.
As the API is the same for both of us, we should be able to build this "wikipedia-ignore" rule in a way that it fits both of our projects.

**Comment by Sandr00** [comment]
Yes, thanks for clarifying. I will create an issue in G4.

**Comment by Sandr0x00** [comment]
Thanks for clarifying @martomi .
@Henni Yes, I think too, that we should work together on this. Let's move this discussion to the API, since we will handle it there. I will create an Issue about this in the API.

**Comment by Sandr0x00** [comment]
Can you close this Issue here? (Do not have rights)
