### ISSUE TITLE
Unstructured Data Website Storage Format

### ISSUE THREAD

**Issue by lukasstreit** [MusicConnectionMachine/RelationshipsG3#23]
**!Please go to [UnstructuredData/#68](https://github.com/MusicConnectionMachine/UnstructuredData/issues/68) for discussion!**

We (Group 2) have been discussing today in what format we should store the websites that we output. To decide on this we would like to ask you and Group 4 for your preferences.

**First Question:** 
Do you want the websites to still contain header information? Otherwise we can just cut out the header fields and only give you actual website content. The headers basically contain metadata about the websites.

**Second Question:**
We can either store each website as a standalone blob(file) or we could put several websites into one or several large blob(s). The first option would allow you to directly access a website but you would basically have to download them one at a time. With the second option there would be less files (although probably equal in total size) for you to download but if you're looking for a specific website you would have to either search for it within the blob or we would have to provide you with an offset.

Please tell us your opinion on each matter, tutors are obviously welcome to share their advice, too :smile:

**Comment by kordianbruck** [comment]
@krishenk please comment in that issue as well and then close this issue when done. 

All discussions please in the other issue - not here.

**Comment by kordianbruck** [comment]
Obsolete cause completed.
