### ISSUE TITLE
Dockerhub / Azure Setup

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/RelationshipsG3#25]
Pulling this from the readme so its on your radar.

@RBirkeland please get on this

**Comment by RBirkeland** [comment]
On it!

**Comment by Sandr0x00** [comment]
I think the Docker-stuff is already done in [MusicConnectionMachine/Relationships](https://github.com/MusicConnectionMachine/Relationships)
@RBirkeland can you verify it?

**Comment by ansjin** [comment]
only the Dockerhub setup is done not the Azure setup!

**Comment by pfent** [comment]
can you update the section of your [readme](https://github.com/MusicConnectionMachine/RelationshipsG3#dockerhub-setup), regarding dockerhub, if this is already done?

**Comment by ansjin** [comment]
shifted here https://github.com/MusicConnectionMachine/Relationships/issues/18
