### ISSUE TITLE
Widget to explore Relationships - Requirements

### ISSUE THREAD

**Issue by lustoykov** [MusicConnectionMachine/RelationshipsG3#27]
# Moved to https://github.com/MusicConnectionMachine/api/issues/33

 I don't have rights, so please add Assigness and Deadline: 02.04.2017
so yesterdey me, @martomi and @vviro had a meeting and here is what came out of the discussion

The basic idea is that we want to display in a somewhat-table view **non-trivial relationships** (almost like a surprise-fun-fact table - Mozart | Liked | Getting Drunk)

`Entity | Relation | Entity`

When a user on the [IMSLP](https://imslp.org/) site and exploring our widget, one of the entities is always fixed (for instance Mozart).

Now we want to have a search bar, where user can type in. The search bar should be very smart and display **autosuggestions** in form of:

**Relations Suggestions**
 - Entity1                         
 - Entity2                        
...                                    
                                       
**Entities Suggestions**
 - Entity1                        
 - Entity2
...
-------------------------
Whenever a user clicks one of the suggestions, we'd make an api call with `Entity | Entity` expecting `relations` as response or `Entity | Relations` expecting `entities` as response to display the table view `Entity | Relation | Entity`

## Requirement: for the autosuggestions

- the API `GET /autosuggest` should accept:
     a single param `query: { 
      primaryEntity 
    }`

- the API should deliver:

```
{ 
   entitites: [ { title: '...', importance: '...', confidence: '...' }, { ... } ]
   relations: [ { title: '...', importance: '...', confidence: '...' }, { ... } ]
}
```

at least `title` is required, `importance` and `confidence` would be nice.

-------------------------------------------------------

## Requirement: for data display

 - The API `GET /relations` should accept:
    a single param `query: { 
        primaryEntity: String,
        secondaryEntity: String,
    }`

and return 
```
{ 
   relations: [ { title: '...', importance: '...', confidence: '...' }, { ... } ]
}
```
 - The API `/entities` should accept:
   a single param `query: { 
        primaryEntity: String,
        relation: String,
    }`

and return

```
{ 
   entities: [ { title: '...', importance: '...', confidence: '...' }, { ... } ]
}
```

@martomi can you double check if the API as defined is OK? Please edit the post directly if I missed something.

@vviro also encourages us to talk to him more often.

**Comment by Henni** [comment]
@lustoykov what do you mean by importance and how is it different from confidence?

I would suggest changing the names `primaryEntity` and `secondaryEntity` to `subject_id` and `object_id`. We might also want to do the same for `relation` and use an ID here as well.

Also the entity 'Getting Drunk' won't show up in our dataset as we only work with a limited amount of entity types (composers, artists, pieces). Activities like this aren't one of them.

**Comment by kordianbruck** [comment]
@lustoykov Please move this issue to the API project. Coding the API endpoint for autocompletion / autosuggest ist part of your tasks not group3.

**Comment by lustoykov** [comment]
OK, we'll code the API, no problem, but they'll need to data mine according to this specification so that the database can have somewhat similar entities

**Comment by kordianbruck** [comment]
@lustoykov yes, they will create the database models that you can utilize for the API endpoints. This is in progress currently. Check the other issues that are open in the API project
