### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by ansjin** [MusicConnectionMachine/RelationshipsG3#30]
Can you add the missing steps for running exemplar algorithm!

**Comment by kordianbruck** [comment]
@krishenk whats your status here? This is a high priority issue and has not been fixed in 3 days? Please do this today!

**Comment by sacdallago** [comment]
Well, if everything is being ported to another repo @kordianbruck better yet do it there? 💭 I'm not sure though, maybe this is something that needs to be addressed here first, later on the joint repo

**Comment by kordianbruck** [comment]
Lets finish up the issues here instead of copying them.

**Comment by ansjin** [comment]
completed here https://github.com/MusicConnectionMachine/RelationshipsG3/pull/32
