### ISSUE TITLE
Relationship definitions

### ISSUE THREAD

**Issue by Henni** [MusicConnectionMachine/RelationshipsG3#4]
which relationships do we want to extract?

This is a great source to get started: https://musicbrainz.org/relationships

**Comment by sacdallago** [comment]
I agree on musicbrainz. The _classical_ world needs some slight alterations in think-wise though. Once you have some more ideas, let's iterate over them with @vviro

**Comment by vviro** [comment]
@Henni great find!

The subject of classical music metadata is very broad, there are way too many aspects that could be covered and we probably need to skip most of them for the time being. For example, the roles of a performing musician (instrumentalist with certain instruments (could be multiple!) or conducting) are very relevant, as well as participating in the same performance or recording is another. But for example certain album releases and relationships related to them are probably out of scope.

One other consideration is the ability to extract entities of certain types with a reasonable certainty, and this is related to the NLP techniques available to us. Things like places, people and dates can probably be extracted rather well using standard techniques and packages, and so we have a good chance to extract the related relationships as well. Things like recordings would probably require more work to get right. So I'd also look at the means with which the relations are going to be extracted.

There are also types of relationships that are certainly not commonly extracted, like for example the teacher-student, or admirer, or competitor relationships, which are still highly relevant to our project. I'd go for them in any case. If they involve easy-to-extract entities, I'd go for such relations first.

I think that it could be very helpful and illustrative if we'd consider a few texts/web pages that we are going to analyze, and see which relationships we would like to extract from them. It's always easier to start with something specific than to draft the plan based on ideas only. To quote von Moltke, no battle plan survives contact with the enemy. Let's have a go at the bottom-up approach - the sooner the better!

**Comment by ansjin** [comment]
As mentioned by @vviro  we need to find some tests/web pages and extract relationships from them. 
But first we also need to define the terms, which will be used for extracting relationship. 

For extraction we can use any of the tools mentioned on this page:
https://thenewstack.io/six-of-the-best-open-source-data-mining-tools/

I think we can start with **NLTK** or **Orange**

**Comment by Henni** [comment]
> As mentioned here https://rostlab.org/owiki/index.php/Javascript_technology_2017#Project_B: 
> define a list of terms for relationships between following entities:
>     Composer - Composer
>     Composer - Music Piece
>     Composer - Musician
>     Music Piece - Music Piece
>     Music Piece - Musician
>     Musician - Musician 
> 
> We can get start with these sources: 
> http://pccrelationshipdesignatortg.pbworks.com/w/page/59518049/Music%20Relationship%20Designators%20(Core%20and%20Full%20lists)
> 
> http://www.rda-jsc.org/archivedsite/workspace/rdaappi_2015february.pdf
> 
> 
> For starting we can use these terms and run NLTK or Orange to extract relationships

@ansjin in #7

**Comment by kordianbruck** [comment]
@Henni can this be closed then?

**Comment by Henni** [comment]
@kordianbruck we have to do some reviewing regarding the relationships in the future.
But yeah, we can close this issue and we'll do this in a new issue then.
