### ISSUE TITLE
Relationship Structure

### ISSUE THREAD

**Issue by ansjin** [MusicConnectionMachine/RelationshipsG3#5]
The Relationship Structure that will be saved in database by our application. 

We currently have decided it to be like this:  

![relationship_structure](https://cloud.githubusercontent.com/assets/10348337/23561300/f3d1bcfc-003d-11e7-82bc-90c50961aff3.jpg)

**Comment by sacdallago** [comment]
Sorry,  I don't understand this diagram.

Can you use standardised UML diagrams? ER schemas are built like: https://www.tutorialspoint.com/dbms/er_diagram_representation.htm

**Comment by sacdallago** [comment]
Ps.: it doesn't specify it in the article but: there are ways of visually representing _weak_ entities, _object keys_ and other items you might need to model your diagram. Just go on googling ER schema how to's if you need any of these

**Comment by ansjin** [comment]
Yeah true, the diagram was pretty unclear. I have tried to give here more info about it and also the ER Diagram. 

**ER-Diagram :**
![relationship_structure-1](https://cloud.githubusercontent.com/assets/10348337/23578881/dcef622a-00e0-11e7-9faa-b1ad0ea48890.png)

**Detail:** 
Here Source to target is a 1 to 1 relationship that can have multiple relationships.

Each relationship has two attributes:

1. **Relationship_Info**: This depicts the information about the relationship between source and target. It further has 3 attributes:

- RelationTerm : It is the basic term used to identify relationship like 'worked with', 'composed by' etc.

- RelationshipType: This tells Relationship type (like composer-composer, Musician-composer etc) of that particular relation term.

- Direction: It tells whether the relationship is bidirectional or unidirectional.

2. **Relation_Quality**: This attribute tells the quality of relationship. It further has 3 attributes:

- SourceURL: This contains the sourceURL link. This could  may be in future contain more information given by group 1 or group 2.

- PageRank: This is a derived attribute, which can be derived from SourceURL and contains the pageRank.

- Count: This stores the count of how many times that relationship is found on the sourceURL page.



**Edit link:**
https://creately.com/diagram/izv6olk32/4UbVGv8EZjFR7pKkbs9soZ6YE%3D

**Comment by kordianbruck** [comment]
It is not really clear war a source/target can or must be. Can you also elaborate on this?

I'm also no sure about the Relaton_Quality. Why is SourceURL required? Will the PageRank only be one field? Wouldn't you have multiple qualities based on each SourceURL?

**Comment by Henni** [comment]
@kordianbruck source and target are both entities as given by  group1 and group2

**Comment by ansjin** [comment]
@kordianbruck 
source/target : As mentioned by @Henni it will be entities given to us by group1 and group2. 

SourceURL:   It is required to mine the relationships in between the entities (provided to us by group1 or group 2) using our relationship terms.  

Page rank : For the time we have thought it as one field, we have to discuss on it further.

multiple qualities: Yes we will be having multiple qualities based upon the source page. 
Our json structure looks something like this : 
![str](https://cloud.githubusercontent.com/assets/10348337/23579875/f95b84aa-00f6-11e7-9a0b-7c25782f9cfa.PNG)

![terms](https://cloud.githubusercontent.com/assets/10348337/23579881/1ef6b43c-00f7-11e7-9b32-5043f80b48aa.PNG)

**Comment by kordianbruck** [comment]
Entities means: composers & musicians but not pieces of work? (Check https://github.com/MusicConnectionMachine/VisualizationG5/pull/7/files)
right?

So is the page rank the rank of the URL linked? Or is it referenced to something else?

**Comment by vviro** [comment]
@ansjin do we already know with which means (algorithms/packages) it is possible to extract which relationships?

**Comment by ansjin** [comment]
@kordianbruck Entities can also be piece of work but then out of the two entities only one will be piece of work while the other one will be from other entities like composer/musician/orchestra. 
and yes the page rank is the rank of the URL linked. 

@vviro No, we have not yet finalized upon the algorithm but the idea is:

- first to define the relationship terms( https://github.com/MusicConnectionMachine/RelationshipsG3/issues/7) for each relationships (https://github.com/MusicConnectionMachine/RelationshipsG3/issues/4) 

- then use those relationship terms(for each relationship) with the algorithm/s (https://github.com/MusicConnectionMachine/RelationshipsG3/issues/3), to extract the relationship between the entities (composer, musician, piece, orchestra etc). 

We will have to try different algorithms and check which algorithms gives best result for which relationship, based upon which we can bind those algorithms with those type of relationship.
If i am somewhere wrong please do correct me ?

**Comment by kordianbruck** [comment]
@ansjin so the URL might be used in multiple relationships. You should then replace that with a reference to a different table/relation so to not have multiple page ranks for each time that this URL will get relevant - or am I missing something?

**Comment by ansjin** [comment]
@kordianbruck yeah you are right we can separately store a different table/relation named page_info(URL, page rank) and others can reference to it.

**Comment by vviro** [comment]
@ansjin It might be useful to first extract the sentences mentioning the interesting entities (and/or the corresponding pronouns) and then use them (and not just the URLs of the pages containing them) as the source references for the relations that will be extracted from them. So, first come the sentences that will serve for mining relations and afterwards we can see what can be extracted from them. It could be easier to define and narrow down the list of extracted relations once we have this rich and condensed data source. It would be super cool if we could extract (at least some subset of) relations in an unsupervised manner based only on grammar (e.g. parse trees) and statistics, instead of defining everything in advance.

**Comment by ansjin** [comment]
@vviro yeah right,  got your point. So If i understood it correctly, based upon the interesting entities we first extract the sentences from the source page and then these sentences serves as our new source and we mine the relations from them.

**Comment by vviro** [comment]
Regarding the page rank I'm not quite sure where are we going to get it from. Compute it ourselves using the HTML data (might be an expensive distraction)? Use a third-party API (probably infeasible given the amount of data we are going to process)? Use our own definition (which is?...) Page rank is a great algorithm that is especially useful when fighting spam. However, in our case spam is probably (hopefully) not a big issue. We might be able to get away with simple counting (how many times a certain relation is being mentioned). Of course, it would be nice to be able to give authoritative sources more weight, but this would be a refinement that might not be necessary and a bit costly to pursue in relation to other interesting directions.

**Comment by vviro** [comment]
@ansjin exactly. Maybe also additionally extract the adjacent sentences that might refer to the interesting entities using pronouns.

**Comment by ansjin** [comment]
@vviro yeah for page rank calculation we require graph model even I am not sure about that how we gonna get that so for the time being we can get away with simple counting (how many times a certain relation is being mentioned) as mentioned by you. 

And yes got the other point also (like the sentences containing he/she/his/him/her and  other pronouns)

**Comment by kordianbruck** [comment]
@ansjin whats your progress here? When can we expect a PR?

**Comment by Henni** [comment]
This discussion has shifted over to the API repo (https://github.com/MusicConnectionMachine/api/issues/28)

Let's keep this open until it is actually done.

**Comment by ansjin** [comment]
https://github.com/MusicConnectionMachine/api/issues/28
