### ISSUE TITLE
Presentation of the topic: " The Storage Question: To SQL or NoSQL? "

### ISSUE THREAD

**Issue by ansjin** [MusicConnectionMachine/RelationshipsG3#6]
As mentioned here https://rostlab.org/owiki/index.php/Javascript_technology_2017#Theme_5

**Description:**
 In a data driven application, one key question is where to persist the data. In the JavaScript world, there are a lot of possible storage concepts: relational, filesystem based, document stores, key-value stores, graph databases and others. Not every type of data fits each database. In this topic, we’ll take a look into the differences and when to use which. Especially what the differences between session and local storage is and when to use cookies. In addition we will see how WebSQL and Sequilize impact the current development of Javascript applications. Finally, we will see if and how we can handle big data with Javascript tools in the frontend as well as in the backend.

**Other Information as mentioned in the mail by Guy:** 
For starters, we will get you to read about the theme you chose to cover and then talk to your teammates about what you read. You and your team will then have to come up with a (roughly) 45 minutes long talk that is about your topic and project, and that you (and your teammates) will present to the rest of us during presentation week March 22 -March 24.

**Comment by ansjin** [comment]
Useful links which I have found: 

**SQL vs. NoSQL**
https://www.sitepoint.com/sql-vs-nosql-differences/
http://www.thegeekstuff.com/2014/01/sql-vs-nosql-db/
https://www.upwork.com/hiring/data/sql-vs-nosql-databases-whats-the-difference/

**Sequelize:**
http://docs.sequelizejs.com/en/v3/

**Other Links:**

http://hebrayeem.blogspot.de/2014/01/making-sense-of-nosql.html

https://dennisforbes.ca/index.php/2010/03/24/the-impact-of-ssds-on-database-performance-and-the-performance-paradox-of-data-explodification/

http://csimms.botonomy.com/2011/05/html5-storage-wars-localstorage-vs-indexeddb-vs-web-sql.html

**Comment by krishenk** [comment]
Thank you @ansjin for sharing the links; I will have a look at the links you mentioned.

**Comment by kordianbruck** [comment]
Why is this still open @MusicConnectionMachine/group-3 !?!?!?!
